// Source of the ACP tap shim, embedded so the built plugin can write it to
// disk wherever it runs without packaging concerns. The shim is spawned as
// the provider command: BB's ACP bridge talks stdio JSON-RPC to the shim,
// the shim forwards everything byte-for-byte to the real agent process
// (`devin acp`), and on the side parses agent→client traffic for usage
// signals the bridge drops:
//
//   - session/prompt responses    → result.usage (draft end-turn usage)
//   - session/update usage_update → used/size plus *_meta token fields
//   - _cognition.ai/*             → agent_stopped, turn_stats, billing
//
// Each captured message is appended as one JSON line to
// <tapDir>/<sessionId>.jsonl. The tap NEVER alters traffic and NEVER lets a
// capture failure take down the pipe: forwarding happens before parsing and
// every capture is wrapped so the worst outcome is a missing stats line.

export const ACP_TAP_FILENAME = "acp-tap.mjs";

export const ACP_TAP_SOURCE = `#!/usr/bin/env node
// Generated by bb-plugin-turn-stats — do not edit, the plugin rewrites it.
// Env: TAP_SPAWN (command line to run, e.g. "devin acp"), TAP_DIR (JSONL out).
import { spawn } from "node:child_process";
import { appendFileSync, mkdirSync, statSync, renameSync } from "node:fs";
import { join } from "node:path";

const SPAWN = (process.env.TAP_SPAWN || "devin acp").split(/\\s+/);
const TAP_DIR = process.env.TAP_DIR;
const MAX_BYTES = 4 * 1024 * 1024;

if (TAP_DIR) {
  try { mkdirSync(TAP_DIR, { recursive: true }); } catch {}
}

const child = spawn(SPAWN[0], SPAWN.slice(1), {
  stdio: ["pipe", "pipe", "inherit"],
  env: process.env,
});

// request id → { method, sessionId } so bare response objects (which carry
// no sessionId) can still be attributed. Bounded: ids are deleted on use.
const pending = new Map();

function tap(sessionId, kind, data) {
  if (!TAP_DIR || !sessionId) return;
  try {
    const file = join(TAP_DIR, sessionId + ".jsonl");
    try {
      if (statSync(file).size > MAX_BYTES) {
        renameSync(file, file + ".1");
      }
    } catch {}
    appendFileSync(file, JSON.stringify({ at: Date.now(), kind, data }) + "\\n");
  } catch {}
}

function inspectClient(line) {
  let m;
  try { m = JSON.parse(line); } catch { return; }
  if (m.id !== undefined && m.method) {
    pending.set(m.id, { method: m.method, sessionId: m.params?.sessionId });
  }
}

function inspectAgent(line) {
  let m;
  try { m = JSON.parse(line); } catch { return; }
  const sid = m.params?.sessionId || m.result?.sessionId;
  if (m.method === "session/update") {
    const u = m.params?.update;
    if (u?.sessionUpdate === "usage_update") {
      tap(sid, "usage_update", { used: u.used, size: u.size, cost: u.cost, meta: u._meta });
    } else if (u && u.sessionUpdate && !String(u.sessionUpdate).includes("chunk")) {
      tap(sid, "update:" + u.sessionUpdate, u);
    }
  } else if (typeof m.method === "string" && m.method.startsWith("_")) {
    const name = m.method.slice(1);
    tap(sid, name.startsWith("cognition.ai/") ? name.slice("cognition.ai/".length) : name.replace(/\\//g, ":"), m.params);
  } else if (m.id !== undefined && m.result !== undefined) {
    const req = pending.get(m.id);
    pending.delete(m.id);
    if (req?.method === "session/prompt" && m.result.usage) {
      tap(req.sessionId, "prompt_usage", {
        usage: m.result.usage,
        stopReason: m.result.stopReason,
        meta: m.result._meta,
      });
    } else if (req?.method === "session/new" || req?.method === "session/load") {
      if (m.result?.sessionId) tap(m.result.sessionId, "session_open", {});
    }
  }
}

let inBuf = "";
process.stdin.on("data", (chunk) => {
  child.stdin.write(chunk);
  inBuf += chunk.toString("utf8");
  let i;
  while ((i = inBuf.indexOf("\\n")) >= 0) {
    const line = inBuf.slice(0, i).trim();
    inBuf = inBuf.slice(i + 1);
    if (line) inspectClient(line);
  }
});
process.stdin.on("end", () => child.stdin.end());

let outBuf = "";
child.stdout.on("data", (chunk) => {
  process.stdout.write(chunk);
  outBuf += chunk.toString("utf8");
  let i;
  while ((i = outBuf.indexOf("\\n")) >= 0) {
    const line = outBuf.slice(0, i).trim();
    outBuf = outBuf.slice(i + 1);
    if (line) inspectAgent(line);
  }
});

child.on("exit", (code, signal) => {
  if (signal) process.kill(process.pid, signal);
  else process.exit(code ?? 0);
});
child.on("error", (err) => {
  process.stderr.write("acp-tap: failed to spawn " + SPAWN.join(" ") + ": " + err.message + "\\n");
  process.exit(127);
});
for (const sig of ["SIGINT", "SIGTERM", "SIGHUP"]) {
  process.on(sig, () => { try { child.kill(sig); } catch {} });
}
`;
